### ISSUE TITLE
Listbox scroll bars have the wrong range

### ISSUE THREAD

**Issue by barneyhawes** [decentespresso/de1app#1]
The lists of profiles, skins, etc don't scroll correctly. The bottom part of the scroll bar is not used.
See discussion on [Decent Diaspora (Basecamp)](https://3.basecamp.com/3671212/buckets/7351439/messages/2343554942).

Repro steps:
- Open settings
- Select Presets
- Select eye/magnifier icon to show whole list
- Drag the scroll bar down. The list reaches the bottom when the scroll bar is at around 70%

This also occurs in the list of Skins, and would happen in other lists which use scrolling.

The problem is the the amount by which the list can be scrolled should be the height of the items that are outside the visible part of the list, not the height of the entire list.

**Comment by barneyhawes** [comment]
Created a Pull request (#2) with the fix for this.

**Comment by barneyhawes** [comment]
Question for @Mimoja (or anyone else): now that this pull request has been accepted, what's the best thing to do with the branch on my fork? I'd like to "close" it but the closest option seems to be to delete it. I assume that will have no ill effects on the Decent code repo... but it would be good to get your opinion.

**Comment by decentjohn** [comment]
Yeah, I think close is fine.

**Comment by decentjohn** [comment]
With 14 items in the listbox, the Weber Spring Clean profile doesn't scroll to the bottom. Only 11 are displayed, and I have to use the mouse scroll wheel to show more.  Confirmed this same problem on the android tablet.


![Screen Shot 2020-12-08 at 10 15 59 AM](https://user-images.githubusercontent.com/11965250/101429634-60387380-393e-11eb-9713-f40b7523baee.jpg)
![Screen Shot 2020-12-08 at 10 15 55 AM](https://user-images.githubusercontent.com/11965250/101429641-64fd2780-393e-11eb-9d39-57923e2e0cfb.jpg)

**Comment by barneyhawes** [comment]
Oh dear.  My first thought is that this might be a rounding error, but that probably wouldn't give an off-by-3 result.
I'm working right now but will take a look when I get a chance.

**Comment by barneyhawes** [comment]
Further suggested improvements to scroll bar implementation:

1. Scroll bar position does not update correctly after adding/removing items
2. Set the scroll bar range and small/large step values according to the number of items. This would need to be updated each time the number of items in the list changes.
3. It is not necessary to implement item highlighting by changing the colour of each item every time the selected item changes. The listbox widget already has properties for colouring the selected item. It does not highlight the current item if you set the selected item before jumping to the page so it appears not to be working. However, setting the selected item after opening the page resolves this. We could remove extraneous code here.

**Comment by decentjohn** [comment]
The beta de1app version has the "Cleaning" profile I'm using to test, so you can test with the same thing.

**Comment by decentjohn** [comment]
I've applied this small patch for now to resolve this issue, to see if it has any side effects.
https://github.com/decentespresso/de1app/commit/cf745a27040715a7265e7cbce073fead3d4584f6
