### ISSUE TITLE
1.34.27: built-in clean function errors out with "can't read "::de1_substate_types(13)": no such element in array"

### ISSUE THREAD

**Issue by physhster** [decentespresso/de1app#100]
When attempting to run the "Clean" function from the Machine tab under settings, the clean sequence appears to start then the following error message appears: https://imgur.com/a/hF2eNZJ

**Comment by jeffsf** [comment]
Should have been resolved by f51bd5ec5bfbc40d06ac01db01c84b04f136219c

**Comment by jeffsf** [comment]
That commit should be available on the Beta channel at this time.

**Comment by physhster** [comment]
Looks good!
