### ISSUE TITLE
add coffee-related icons to fonts

### ISSUE THREAD

**Issue by barneyhawes** [decentespresso/de1app#12]
It is would be handy to include vector icons in the TTF font files that ship with the app. 

This will provide a simple, low-overhead way to dynamically include a vector icon as part of the UI.
It also allows icons to be included in the middle of a sentence (eg for instructional text).

John suggested that we add some icons to the notosansui font which is used in the app.
I'd like to propose that we add the same icons to all fonts that ship with the app, at the same unicode points.

I've already drawn vector icons for temperature, espresso*, hand* (stop), flush*, water*, menu, steam*, ratio, bean and grind. (* indicates icons that are based on the Decent UI; others are intended to be consistent with these).

I previously replaced some of the currency symbols with these coffee-related symbols, but there may be a better place to put them. I'm not sure if there is best practise for custom (unofficial) extensions to the unicode character set?

**Comment by barneyhawes** [comment]
Looks like someone thought of this already: https://en.wikipedia.org/wiki/Private_Use_Areas
I'll look into it and report back.

**Comment by barneyhawes** [comment]
OK, I have relocated the symbols to the private area of the fonts used for [Metric](https://github.com/barneyhawes/decent-metric/commit/1ea117561e17ef9922536b9c9e73fa7b257e0fef).
We can add these to the main Decent codebase if we wish.
Questions:
1. Where should the symbol constants be defined? Perhas in Utils, where other font-defining code lives?
2. Which fonts shouldbe modified? Only notosansui (in two variants), or others?
3. Are there any more symbols to add to the set? I suggest that we add symbols for "Tea" and "Filter coffee" - any others?

**Comment by decentjohn** [comment]
I love this, and it also would solve some code complexity that current exists with the Thai, Arabic, Hebrew versions, that use their own fonts and don't have all the necessary icons (like a checkedbox) 

Having the buttons from icons on the GHC makes a lot of sense.  There's a need for checked and unchecked boxes, USB, bluetooth, wifi icons.

It'd be nice to have icons for "stars" so you can rate things.  Thumbs up/down icons too.

![download](https://user-images.githubusercontent.com/11965250/97066677-d7fa4b00-15e9-11eb-881f-3985dd9b3bfa.png)


![download-1](https://user-images.githubusercontent.com/11965250/97066676-d6c91e00-15e9-11eb-8629-fc5d8c84368c.png)

**Comment by barneyhawes** [comment]
OK, good stuff. I'll work on adding the following:
- Tea
- Filter coffee
- Star (filled)
- Star (outline)
- Thumb up
- Thumb down
- Checked box
- Unchecked box
- Bluetooth
- WiFi

I'd also like to add an icon for a profile/preset - but have not been able to come up with a good icon representation for this.

**Comment by decentjohn** [comment]
The settings icons are not great, I feel.

Preset - it's a checklist currently
Machine - because it doesn't look like a DE1
Profile - looks like an EQ, which I guess is ok, but the shape of it is just wrong.

**Comment by decentjohn** [comment]
Font Awesome 6 just went "alpha 1" -- Barney you might want to take a look to see if there's good stuff in there.
https://drive.google.com/file/d/1Zzs15pOB5A8RXTR13o4dNOwuAB-dGSFN/view?usp=sharing

I did a quick look for coffee and tea

![Screen Shot 2020-10-30 at 9 30 28 AM](https://user-images.githubusercontent.com/11965250/97649793-2d73a380-1a93-11eb-900e-77c24043a3cf.jpg)
![Screen Shot 2020-10-30 at 9 32 00 AM](https://user-images.githubusercontent.com/11965250/97649795-2fd5fd80-1a93-11eb-8f65-af80d4df5e42.jpg)

**Comment by barneyhawes** [comment]
I had a go at iconifying (not a word) the DE1 and the Niche Zero to create icons for coffee machine and grinder.
![image](https://user-images.githubusercontent.com/853713/97910100-25409000-1d41-11eb-9bda-038277fb25e7.png)

Whilst they are simplified and not-to-scale, I think they are still a bit too realistic and detailed. They don't work when reduced to a very small size - you can see this when placed alongside the other icons:
![image](https://user-images.githubusercontent.com/853713/97910265-6a64c200-1d41-11eb-9da4-7ac4b4ba5634.png)

I'll keep trying to simplify them, and draw out (no pun intended) the character of the machines.

In the meantime, comments are welcome. Also, it would be good to think about where assets should be uploaded for sharing and developing. I'd like to upload vector image files, font files, etc - but don't want to pollute the codebase with this stuff.

**Comment by barneyhawes** [comment]
I added icons for stars, checkboxes, tea, filter, bluetooth, wifi.
Brought back in coffee, temperature and grind size (bit abstract that one).
I imagine it would be useful to have a battery icon, will do that too.
Didn't manage to produce a satisfying thumbs up/down yet.
![image](https://user-images.githubusercontent.com/853713/97917476-6ee2a800-1d4c-11eb-92e3-0142a36ea3a6.png)

**Comment by decentjohn** [comment]
The Niche icon is quite nice.

On the DE1 icon, some changes that might help:
- remove the support on the tablet (no longer on DE1 models)
- move the GH closer to the body
- make the body a little bit wider
- shorten the leg extension a little bit
- thinner steam wand

**Comment by decentjohn** [comment]
I tried...

![x2](https://user-images.githubusercontent.com/11965250/97937349-696f7700-1db9-11eb-83fe-087c2f11bdde.jpg)

**Comment by decentjohn** [comment]
To compare, here's an actual profile DE1 in black:

**Comment by marcello3d** [comment]
Maybe remove the steam wand and extra handle for simplicity. And thicker drip tray area in front

**Comment by barneyhawes** [comment]
Good feedback. I'll remove the extra handle and tablet stand.
I deliberately made the body thinner, the group head larger, moved the steam wand between the group head and body, and increased the leg stand size because these features define the silhoutte - but I'll happily revisit it and see if I can get the balance a bit better. 
It's also worth viewing them smaller (try zooming out in the browser) because these icons will normally be seen much smaller than the previews above - small details disappear but you want to be able to recognise it even when it is just a few pixels across.

**Comment by barneyhawes** [comment]
Here's an updated Decent icon:
![image](https://user-images.githubusercontent.com/853713/98287581-72b93900-1f9d-11eb-9274-e2c8be0182a1.png)

You can see the evolution of the icon over 3 iterations:
![image](https://user-images.githubusercontent.com/853713/98287648-8b295380-1f9d-11eb-92b0-6a03b97ff14a.png)

Here you can see how it looks without a steam wand (I prefer it with, but it was suggested):
![image](https://user-images.githubusercontent.com/853713/98287692-a1371400-1f9d-11eb-8503-504fb4d0c45f.png)

And here's how it looks when it is small:
![image](https://user-images.githubusercontent.com/853713/98287770-bf9d0f80-1f9d-11eb-8295-3ffb179d8b88.png)
And really small:
![image](https://user-images.githubusercontent.com/853713/98287850-e22f2880-1f9d-11eb-8d48-7957916ff946.png)

**Comment by barneyhawes** [comment]
Battery icons (0%, 25%, 50%, 75%, 100%):
![image](https://user-images.githubusercontent.com/853713/98297880-06decc80-1fad-11eb-9b40-b27e0c2cfeff.png)

**Comment by decentjohn** [comment]
The DE1 icon looks nice.  How about angling the tablet a bit more?

![iconbig](https://user-images.githubusercontent.com/11965250/98311099-8b5f3880-2009-11eb-84ee-f5cb66d14eb1.jpg)
![iconsmall](https://user-images.githubusercontent.com/11965250/98311102-8c906580-2009-11eb-8e2f-ae9d8ef940ea.jpg)

**Comment by barneyhawes** [comment]
No problem - what angle would you like (from vertical)? 
I think it is 15° at the moment. Your mockup looks to be approx 45°.

I'll share the vector files, so it would be easy to adjust or reuse these. I'm not sure where to upload them to - any suggestions?

**Comment by barneyhawes** [comment]
All icons have been added to the Mazzard font used in Metric so we can see how they look alongside text and adjust sizes, spacing, etc.
![image](https://user-images.githubusercontent.com/853713/98383767-cfbbfa00-2044-11eb-8194-a1b596123bad.png)

The "tea" symbol is too detailed for small sizes (this is size 28) and the Niche is a bit unclear at this size. Others looking good to me.

**Comment by decentjohn** [comment]
The "psd" subproject is a bit mis-named, as it's really "high resolution source files", and I think that's where your originals should live.  Maybe make a ./psd/icons/ directory and add that to the rep?

ps: I really like how your de1 icon ended up.

![Uploading Screen Shot 2020-11-07 at 4.46.56 PM.jpg…]()

**Comment by barneyhawes** [comment]
Here is the Google font with the added private symbols (I had to put it in a zip to upload here).

[notosansuiregular.zip](https://github.com/decentespresso/de1app/files/5612806/notosansuiregular.zip)

The unicode constants for the symbols are:

```
set ::symbol_temperature "\uE000"
set ::symbol_espresso "\uE001"
set ::symbol_hand "\uE002"
set ::symbol_flush "\uE003"
set ::symbol_water "\uE004"
set ::symbol_menu "\uE005"
set ::symbol_steam "\uE006"
set ::symbol_ratio "\uE007"
set ::symbol_bean "\uE008"
set ::symbol_grind "\uE009"
set ::symbol_tick "\uE00A"
set ::symbol_box "\uE00B"
set ::symbol_box_checked "\uE00C"
set ::symbol_star "\uE00D"
set ::symbol_star_outline "\uE00E"
set ::symbol_tea "\uE00F"
set ::symbol_filter "\uE010"
set ::symbol_de1 "\uE011"
set ::symbol_niche "\uE012"
set ::symbol_battery_0 "\uE013"
set ::symbol_battery_25 "\uE014"
set ::symbol_battery_50 "\uE015"
set ::symbol_battery_75 "\uE016"
set ::symbol_battery_100 "\uE017"
set ::symbol_bluetooth "\uE018"
set ::symbol_wifi "\uE019"
```

**Comment by Damian-AU** [comment]
Love your work with these fonts 👍

**Comment by decentjohn** [comment]
Accepted and published in today's beta.

Could you perhaps put a USB icon in there?  I note that your icons are smaller, and more appropriately sized, than the icons in the font we previously used, and now the USB icons is much larger than the BLE and Wifi icons.

![Screen Shot 2020-11-30 at 2 01 29 PM](https://user-images.githubusercontent.com/11965250/100575273-b7bf5980-3316-11eb-8075-fe6582f37120.jpg)

**Comment by barneyhawes** [comment]
USB icon added.

![image](https://user-images.githubusercontent.com/853713/100595293-a2383880-32f2-11eb-94a8-4b475a79092d.png)

Unicode character constant: `set ::symbol_usb "\uE01A"`

Download: [notosansuiregular.zip](https://github.com/decentespresso/de1app/files/5615164/notosansuiregular.zip)

**Comment by barneyhawes** [comment]
I have created a pull request on the PSD sub-project with the symbols and modified fonts.
https://github.com/decentespresso/de1plus_psd/pull/1

**Comment by decentjohn** [comment]
all good.

![Screen Shot 2020-11-30 at 7 32 39 PM](https://user-images.githubusercontent.com/11965250/100605434-e18e7580-3342-11eb-86cb-3157cd21cdc8.jpg)

**Comment by decentjohn** [comment]
https://github.com/decentespresso/de1app/commit/0e0dbbb6a9070c12bc1fbea9fe20808114354c95
