### ISSUE TITLE
`Content-type` of POST in visualizer_upload/plugin.tcl has wrong format

### ISSUE THREAD

**Issue by stassinari** [decentespresso/de1app#124]
I'm currently adapting the `visualizer_upload/plugin.tcl` file for a side project I'm building, and I've noticed that the `POST` request made to visualizer.coffee has a slightly wrong format ([link to line](https://github.com/decentespresso/de1app/blob/main/de1plus/plugins/visualizer_upload/plugin.tcl#L129))

Instead of:
```
multipart/form-data, charset=utf-8, boundary=$boundary
```

it should be semicolon separated (see [RFC: 7231, section 3.1.1.1](https://tools.ietf.org/html/rfc7231#section-3.1.1.1)):
```
multipart/form-data; charset=utf-8; boundary=$boundary
```

I know it's a small thing (and apparently it's an issue that has been worked around for visualizer.coffee), but it made the request incompatible both with a library I'm using to parse the `multipart/form-data` body (busboy for NodeJs) and with the Firebase Functions I'm using.

I could quickly make a PR, but:
1. I don't want to do something that is not needed and create more work for people
2. (I assume it) needs coordination with Miha to update the code that parses the request on his end

**Comment by ebengoechea** [comment]
I remember noticing this when I adapted the code for the Describe Your Espresso plugin, but I think when I tried ";" the shot would not upload correctly (probably because, as you said, @miharekar had adapted his code to handle it like this).

**Comment by Mimoja** [comment]
I had it with a ; originally. Did not work back then

**Comment by stassinari** [comment]
Using `;` from local apparently works, so it could be a simple replacing, but probably @miharekar knows something that I don't ^_^

**Comment by miharekar** [comment]
I didn't touch anything, this is all Ruby/Rails internals 😅 

I think it did not work because we were missing some other things that then Jakub fixed?

Dunno TBH 😬

But if it's valid form post, then it _should_ just work.

**Comment by Mimoja** [comment]
Closing as this has been tested to work and the per-spec correct way does not. meh
