### ISSUE TITLE
Better support for slow/bad Internet connections

### ISSUE THREAD

**Issue by beettlle** [decentespresso/de1app#128]
I have a 3Mbps DSL connection that is very flaky so any operations that goes over the internet is a problem.

Would be great if the following 2 things were possible:
1. For me not only takes a long time but is always at risk of stalling due to drops in connection.  Would be great to have a "download firmware" procedure in the app so I could take the tablet somewhere else, download the firmware, and then do the process locally.  Either that or let it download overnight and start the update process in the morning (after coffee of course).
2. Would be great to have a more rsync/git like way of downloading the app to the tablet.  Right now I have to start from scratch every time the tablet app update stalls or fails.

**Comment by decentjohn** [comment]
Just yesterday I made the app update much more robust so it picks up where the last attempt failed, and it also tries each file 3 times.  It's in the nightly version now.
