### ISSUE TITLE
Temp/time garbage after flush

### ISSUE THREAD

**Issue by nicpottier** [decentespresso/de1app#15]
Immediately after flush some temp and a timer appear in lower right on flush screen. Not sure if they are meant to be there or if that is debug output or what but at the very least it seems to be in the wrong place / overlapping.

![PXL_20201025_160113486.jpg](https://user-images.githubusercontent.com/168067/97112293-af815800-16a0-11eb-93df-b512d83b67bb.jpg)

Happy to take a look if that would be useful.

**Comment by Mimoja** [comment]
Are you on beta or stable?

**Comment by nicpottier** [comment]
Stable, thought I had switched to beta but didn't realize I had to hit update afterwards. Looks like it is fixed in beta so closing. Thanks!

**Comment by Mimoja** [comment]
nice :)
