### ISSUE TITLE
ble listboxes need scrollbars

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#17]
At the korea coffee show, there were so many acaia, felicita and other scales, that Skale was never in the top few to pick from.  

So... we need to add scrollbars to the ble pick lists, for this odd case.

**Comment by Mimoja** [comment]
lol. amazing :3

**Comment by barneyhawes** [comment]
John - thanks for bring in these changes. You can close this issue now.
FYI - it would have closed automatically if you'd accepted the pull request instead of duplicating the changes. Between us we'll figure out the best ways to use Git!
