### ISSUE TITLE
missing file in DSX

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#173]
could not read "./skins/DSx/DSx_Plugins/move_on_button.off": no such file or directory
from:
https://decentespresso.com/nightly.log

NOTICE: Updated version to 1.36.5.67 from 1.36.5
diff --git a/de1plus/version.tcl b/de1plus/version.tcl
index b760a54..712b23a 100644
--- a/de1plus/version.tcl
+++ b/de1plus/version.tcl
@@ -1,3 +1,3 @@
-package ifneeded de1app 1.36.5 {}
+package ifneeded de1app 1.36.5.67 {}
 
 set ::changelog_link "https://public.3.basecamp.com/p/M8uUwucqbNrL1fBB1JL9E6fF"
Updating apps
Calculating SHA256 for ./version.tcl ... Copying version.tcl -> /d/download/sync/de1nightly/
Calculating SHA256 for ./build-info.txt ... Copying build-info.txt -> /d/download/sync/de1nightly/
could not read "./skins/DSx/DSx_Plugins/move_on_button.off": no such file or directory
    while executing
"file mtime $source"
    (procedure "make_de1_dir" line 1036)
    invoked from within
"make_de1_dir "." [list "$synctarget/$release_target"]"
    invoked from within
"if {[lindex $argv 1] == "1"} {
	puts "Updating apps"

	# old comment - optionally purge the source directories and resync
	# do this if we remove file..."
    (file "../misc/makede1.tcl" line 39)
Calculating SHA256 for ./skins/DSx/DSx_Code_Files/DSx_skin.tcl ...

**Comment by Damian-AU** [comment]
./skins/DSx/DSx_Plugins/move_on_button.off has been deleted, it is no longer required as the code it contained has been transferred to DSx_skin.tcl

**Comment by decentjohn** [comment]
Gotcha, so we'll remove it from our list of files to copy.

**Comment by Damian-AU** [comment]
Yes please

**Comment by decentjohn** [comment]
Done 
https://github.com/decentespresso/de1app/commit/6bf052321ce753cf87d627047b13f88e65d1988f
