### ISSUE TITLE
MimojaCafe fails to load 

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#176]
On my mac, with both Tk and undroidwish

![Screen Shot 2021-06-28 at 11 17 27 AM](https://user-images.githubusercontent.com/11965250/123574507-8e11d680-d802-11eb-9ede-09d74144ed6e.jpg)

**Comment by ebengoechea** [comment]
Solved with #179

**Comment by Damian-AU** [comment]
> Solved with #178

Confirmed
