### ISSUE TITLE
DSX broken in nightly in undroidwish

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#177]
![Screen Shot 2021-06-28 at 11 25 37 AM](https://user-images.githubusercontent.com/11965250/123575209-d54c9700-d803-11eb-85aa-54af07fd9dde.jpg)

The bottom right graphics are a bit messed up and the buttons there don't work right. Other buttons do work right.

Wondering if this is a dui issue @ebengoechea

**Comment by ebengoechea** [comment]
Will look into it later today

**Comment by ebengoechea** [comment]
@decentjohn I can't replicate, I'm seeing that screen correctly on nightly, both on PC (undroidwish) and tablet (androwish). Was this while testing some image resizing or something?

@Damian-AU, any hint why this may happen?

**Comment by Damian-AU** [comment]
Was it after changing the screen resolution?
Looks like 2 images have been resized up to full screen res.

**Comment by decentjohn** [comment]
That's on my mac, running undroidwish, at 1280x800.

But... if it's working fine for you on your desktop, no problem --maybe I caused this problem and it's unique to me.
