### ISSUE TITLE
one dui translation string breaks things

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#179]
The carriage return in this piece of text, is breaking my translation.  Can you split this up into separate lines? My code doesn't support CRLF inside translatable text.

Also, "writters" is mis-speller.

@ebengoechea 

"A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." {en "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." kr "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." fr "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." de "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." de-ch "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." it "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." ar "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." da "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." sv "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." no "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." he "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." es "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." pt "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." pl "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." fi "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." zh-hans "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." zh-hant "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." th "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." jp "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." el "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." sk "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." cs "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." hu "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." tr "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." ro "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." hi "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." nl "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." ru "A skin-independent, "themable", GUI "mini framework" for skin and plugin writters.
Simplify page creation, auto-adapt aspect to current skin/theme, ready-made widget combos and full-page field editors." }

**Comment by ebengoechea** [comment]
@decentjohn This text is the description of the old DGUI extension, which was in last Stable but should not be in Beta/Nightly, I think it shouldn't appear on your translations?

**Comment by decentjohn** [comment]
Ah, looks like an old remnant then, good.
