### ISSUE TITLE
causing error with MimojaCafe 1/2/3/4 buttons

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#186]
@Mimoja 

I caused this by accident, not sure how, but I can also recreate it by:

1) deleted settings. tdb
2) run de1app and switch to MimojaCafe as skin
3) then go to settings and tap "1" button

Suggested solution is to check that the current profile is saved, ie that settings(profile_filename) is defined.

![Screen Shot 2021-07-24 at 5 57 57 PM](https://user-images.githubusercontent.com/11965250/126865078-e7663d85-68ab-4193-a684-fc510ec23bf2.jpg)

**Comment by Mimoja** [comment]
ack, looking
