### ISSUE TITLE
"Run when ready" option

### ISSUE THREAD

**Issue by beettlle** [decentespresso/de1app#19]
When making tea or pour-overs I turn on the machine and start the process of setting up for tea/pour-over.  Almost every time I am done before the machine is up to temperature and I'm stuck at the "Wait" stage.  

This probably doesn't work with espresso but would be great to have a way to tell the machine to start the tea/pour-over "shot" when it's ready so I can walk away and come back when it's done.  Could be something that is added to the profile so this feature is only enabled for those things that can use it.

**Comment by decentjohn** [comment]
I don't think we could do this, as it would not be in compliance with EU/UL safety rules.  You must be proven to present when boiling water comes out.
