### ISSUE TITLE
Arabic font text entry too tall

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#202]
![Screen Shot 2021-10-29 at 4 24 27 PM](https://user-images.githubusercontent.com/11965250/139401912-d56bfa6b-a08f-4145-b8ff-c367aeaa5973.jpg)

The Arabic font has very tall carriage returns, so that this page has too large an entry box.

The dui solution uses the same adjuster as for listboxes, but it seems like font height is different for listboxes and multiline text entry.  

ie, this did not solve anything since listbox_length_multiplier is not adjusted for arabic font.
-height [expr {int(12 * $::globals(listbox_length_multiplier))}] 

I think we need a new 
multiline_text_height_multiplier

variable in dui to cope with this, and for arabic it should be set to 0.85 or so.

@ebengoechea

**Comment by decentjohn** [comment]
Awesome solution, thanks for teaching me about Tk!

I've done this, but I'm confused as to why absolute canvas measurements are working on all app resolutions:
-canvas_height 730 -canvas_width 2070 

I would have thought I'd need to rescale them, but it appears not.  Screen pics at various resolutions attached.

I'll commit this now and then look at word wrapping.  I've avoided it because it breaks editing, but let me give it a try...

![Screen Shot 2021-11-01 at 2 04 35 PM](https://user-images.githubusercontent.com/11965250/139628953-acb0c3d7-d5b7-44a3-8daa-9b46d4cf98fa.jpg)

![Screen Shot 2021-11-01 at 2 03 59 PM](https://user-images.githubusercontent.com/11965250/139628961-615e56ac-1c85-412f-865e-cd6e518c9124.jpg)

**Comment by decentjohn** [comment]
Word-wrap implemented, thanks!
![Screen Shot 2021-11-01 at 2 38 59 PM](https://user-images.githubusercontent.com/11965250/139631696-654335b9-6b05-42cd-ae51-4fc6f986133a.jpg)

**Comment by ebengoechea** [comment]
DUI always rescales _all_ options related to positions and dimensions in exported commands, to simplify client code. Never need to rescale when you use DUI commands, it's done automatically for you.
