### ISSUE TITLE
make zint library not required

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#203]
@ebengoechea in two places you require zint, which makes the app not work on desktop OSes that don't have it as part of the standard library.   I haven't been able to find zint for tk for Macos, precompiled, for example.   

I added a catch around the uses of it, so that there's a graceful degradation in this case.

catch {
    package require zint
}

but you may want to handle this in a different way.

As we want the app to work well on many OSes, and this is the only issue at the moment, this seems worth doing.

**Comment by ebengoechea** [comment]
Perfect. I warned about the new required package in the comments of the commit that included it for the first time, as I suspected it could happen, but didn't want to catch it until confirming it was a real problem in some system.

**Comment by ebengoechea** [comment]
@decentjohn Solved by PR #204 in visualizer_upload

**Comment by ebengoechea** [comment]
@decentjohn And solved by PR #205 in DYE

**Comment by ebengoechea** [comment]
Closed #204 #205
