### ISSUE TITLE
Are de1.tcl and de1c.tcl in a good shape?

### ISSUE THREAD

**Issue by Mimoja** [decentespresso/de1app#21]
It seems like they should be calling de1plus.tcl directly. Is it worth maintianing them seperately instead of loading de1plus.tcl from within?

**Comment by decentjohn** [comment]
Both those scripts are obsolete, and I think they could be removed.

They originate from an old time when I was planning a separate DE1 and DE1+ model, with the DE1 having fewer features.  And the Insight skin was originally called the Creator skin (Baaaad name!).

I think it's possible to remove 
create_de1_icon.tcl

as well.

I think de1.tcl could be removed from misc.tcl, which lists the files in the distro:

        de1.tcl *

the de1plus.tcl app should probably be renamed to de1app.tcl but that would likely break things for no user-facing benefit, so I'd vote to not bother.

Same thing for the app directory, it could have been /de1app/ on Android tablets instead if /de1plus/, but again, changing that will just break things for no benefit.

**Comment by barneyhawes** [comment]
Have you decided for sure to never release a DE model? If so, let's create a separate ticket for removing the code than handles reducing functionality for this model and I'll do it.
