### ISSUE TITLE
Time changes require app restarts

### ISSUE THREAD

**Issue by jetuser** [decentespresso/de1app#23]
I had to manually override the timezone on the tablet as it was guessing my timezone incorrectly (thought I was on MST rather than PST which is odd as this is the first device to ever do that). When I did that, it looks like the decent app was stuck on the old timezone rather than the new one requiring me to exit the app and restart it to get the correct time.

It's a minor issue, but a nice one to fix if feasible.

**Comment by decentjohn** [comment]
It's unfortunately not feasible to fix.  The Timezone is read by Tcl upon app startup and never re-read.  I've looked at this bug in the past in some detail.
