### ISSUE TITLE
Problem with visualizer_upload extension

### ISSUE THREAD

**Issue by EchoPark** [decentespresso/de1app#235]
I met some problem with the visualizer_upload extension in DE. I am sure I use the right user name and password but it still tells me "Upload failed！ERR could't open socket: permission denied."

the DE app version is v1.38.6.7 nightly, and I am sure the network is ok. turning wifi off and on or change to other wifi can't solve the problem too.

the problem always happen when I use my MI tablet(MI 5 Pro). and in DE tablet the function works well.

**Comment by ebengoechea** [comment]
This is a wifi or connection problem on the tablet, nothing we can change on the app to solve it.

**Comment by EchoPark** [comment]
I try to access visualizer.coffee with this wifi and it works well, then I open the app to use the extension to upload my shot, it tells me the error message as I mention.

**Comment by EchoPark** [comment]
can lose the issue, I find my tablet forbid the app access to network, but I still can use the app to update solfware, interesting!
