### ISSUE TITLE
Step weight maximum

### ISSUE THREAD

**Issue by Phoenixxx3** [decentespresso/de1app#241]
Every time I set a maximum weight in one step of a profile, this maximum is also applied to all following steps. I don't think this is intentional.

**Comment by decentjohn** [comment]
Yes this is how @Mimoja programmed it, intentionally.

**Comment by decentjohn** [comment]
Ah, we might be talking about different things.  I meant that the weight is since-the-start, and not per-step.

I'm not finding that setting Weight maximum on a step is effecting later steps. I just tested it.

**Comment by decentjohn** [comment]
@Phoenixxx3 is this bug apparent in the GUI, or is it something that only appears when the shot is run?

**Comment by Phoenixxx3** [comment]
I tried it with the newest nightly on my machine and also on the app on windows that I use for testing.
It changes all following steps immediately.

**Comment by decentjohn** [comment]
Are you talking about this control? Or something else?

Are you using DFLOW or any other extension?

<img width="1280" alt="Screen Shot 2022-02-18 at 2 47 40 PM" src="https://user-images.githubusercontent.com/11965250/154771463-d1610455-fd3b-47ca-9afa-476458951e09.PNG">

**Comment by decentjohn** [comment]
Can you try switching to Insight Skin to see if the bug continues to exist?

I did exactly your steps above, and cannot cause the problem.

DSX is buggy on my mac, and will not let me run settings, so I cannot test your scenario above with DSX.

<img width="1280" alt="Screen Shot 2022-02-18 at 3 00 39 PM" src="https://user-images.githubusercontent.com/11965250/154772395-f7ad81aa-88e0-4862-9a78-cca258a7aec3.PNG">
.

**Comment by Phoenixxx3** [comment]
Oh wow, you are totaly right. It does not happen with Insight, but it will again as soon as I switch back to DSx.
Thank you and sorry for the effort. My issue is apparently in the wrong git repo.

**Comment by decentjohn** [comment]
Glad we got to the root of it.

Can you ask Damian to take a look at it?

**Comment by Phoenixxx3** [comment]
Yes, I am on it. Thanks again!
