### ISSUE TITLE
Swap warmup <-> filltank state transition 

### ISSUE THREAD

**Issue by zygopleural** [decentespresso/de1app#243]
Not sure if this is the correct place to give feedback like this, but here goes (this is based on feedback from several colleagues and myself)

> FYI, I did take a quick scan through the repo, but couldn't figure out where the code specific to this part of the setup phase is located. If someone could point me in the right direction, happy to open a PR.

# Expected behaviour

When turning a machine on, it should check water levels before warming up.

# What currently happens

It warms up first, then checks water levels.

# Why is this annoying?

Once I have eagerly waited for it to have warmed up, I want to just press the button to make a coffee; but instead I am told that water is low and I have to leave the station to go and find more water to fill the tank. 

Would be a much nicer experience to just do all the prep first and never have to leave the station again.

**Comment by decentjohn** [comment]
Recommend you buy a refill kit, which then adds water as needed, and that solves this.

**Comment by decentjohn** [comment]
feedback received, but this github is for bugs, so I am closing this.
