### ISSUE TITLE
Tap area for dtoggle is a bit too far down

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#244]
This is with undroidwish, but I seem to feel a problem like this with the android tablet too

https://user-images.githubusercontent.com/11965250/171610264-fe4d801e-d236-499e-9adb-f72d8eae15ae.mov

The problem is clear with a less tall dtoggle, but it happens with nornal sizes too

`dui add dtoggle "steam_1 steam_3" 1500 1210 -height 36 -width 80 -anchor nw -variable ::de1(steam_disable_toggle) -command disable_steam_toggle 
`

**Comment by decentjohn** [comment]
Note that I work around this bug by making a clickable area that encomposes the control and its label, so that clicking the label toggles it as well, like HTML controls work.


`add_de1_button "calibrate3" { set ::settings(insert_preinfusion_pause) [expr {!$::settings(insert_preinfusion_pause)}] } 1350 660 1950 720`

such as:
![Screen Shot 2022-06-02 at 12 58 29 PM](https://user-images.githubusercontent.com/11965250/171624493-95fc0abb-1aca-4aad-87d4-cab29941f9c4.JPG)

**Comment by ebengoechea** [comment]
I think the bug is in line 7951 of dui.tcl, the second coordinate should be ```{$y y **-** 12}``` but it is ```{$y **+** 12}```.

Change it if you wish, otherwise I'm make a PR in the weekend.
