### ISSUE TITLE
dtoggle didn't update its visual state

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#251]
In the case below, I wanted to replace a Tk checkbutton with a dtoggle. I've done this in many other places.  The problem appears to be related to the variable being used here.  With a different variable name, it worked fine.

I've made a video to show you how I implemented both controls.  The dtoggle is affecting the variable correctly, it just isn't displaying the correct on/off value on itself.

This is low priority, as I can just continue to use a checkbutton in this use case.

To recreate, there is code in de1_skin_settings.tcl that implements the same control, two ways.  You can uncomment the code below and comment out the first line, to swap the implementations.

```
add_de1_widget "settings_2c" checkbutton 1600 830 {} -text [translate "4: Move on if..."] -padx 0 -pady 0 -indicatoron true  -font Helv_9_bold -anchor nw -foreground #7f879a -activeforeground #7f879a -variable ::current_adv_step(exit_if)  -borderwidth 0  -highlightthickness 0  -command save_current_adv_shot_step -selectcolor #f9f9f9 -activebackground #f9f9f9 -bg #f9f9f9 -relief flat 
# for some reason, use of a dtoggle here is buggy below, the dtoggle does not update its visual state, but otherwise works fine
# add_de1_text "settings_2c" 1700 830 -text [translate "4: Move on if..."] -font Helv_9_bold -fill "#7f879a" -anchor "nw" 
# dui add dtoggle "settings_2c"  1600 840 -width 80 -height 40 -anchor nw  -command save_current_adv_shot_step  -variable ::current_adv_step(exit_if) -tags xyz
# add_de1_variable "settings_2c" 2220 840 -text "" -font Helv_9_bold -fill "#7f879a" -anchor "nw" -textvariable {$::current_adv_step(exit_if)}

```

https://user-images.githubusercontent.com/11965250/171725947-7e10c7a9-fc98-4c34-8d29-0062bf53bfeb.mov

**Comment by ebengoechea** [comment]
My guess: dtoggle works by setting a trace on the target variable when creating the widget. May be the case that ```::current_adv_step(exit_if)``` is deleted and recreated through the lifecycle of the app, thus losing the trace?

**Comment by decentjohn** [comment]
Yes! Indeed you must be right, because that variable gets set/unset as the person moves between advanced profile steps.

**Comment by decentjohn** [comment]
Yes, using a shadow variable fixed this
