### ISSUE TITLE
does "previous values" actually work on open_dialog ?

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#252]
I've never seen this field populated with anything, including when I use DYE.

![Screen Shot 2022-06-03 at 11 16 40 AM](https://user-images.githubusercontent.com/11965250/171835852-c242cd4a-3ece-4e1d-bf01-5b8cd47e0b69.JPG)

**Comment by ebengoechea** [comment]
It's an input argument, invoking code needs to pass the values, there's no "automagic" logic to fill it.

**Comment by decentjohn** [comment]
Ah, I see. I didn't find any mention of "previous" in the docs.

Is there a code sample somewhere?  I am guessing  it's just a 

-previous_values [list 1 2 3]

kind of thing?

**Comment by ebengoechea** [comment]
Yes, exactly like that.

**Comment by decentjohn** [comment]
Ok, great, I see that works!  

Is there a reason not to build this ability directly into the object itself and have it work automatically? For example, using a global array keyed to the variable name?

**Comment by decentjohn** [comment]
That's why I was asking.  It's true that when sqlite is available, you can use that to generate your previous list.
