### ISSUE TITLE
Incorrect beverage type format for cleaning x 5

### ISSUE THREAD

**Issue by puranzhang** [decentespresso/de1app#257]
Halo the team. This came to me couple of times (whenever I update/restore the app) — the `beverage_type` for the cleaning x 5 profile is cased incorrectly (should be `cleaning` instead of `Cleaning`):

https://github.com/decentespresso/de1app/blob/9b60ca14d8c45945441a9c95a97ab9bceeebf004/de1plus/profiles/Cleaning_forward_flush_x5.tcl#L34

and as a result, the Visualizer Upload plugin would not be able to recognize this profile correctly as cleaning ones, and would fail skipping the uploading:

https://github.com/decentespresso/de1app/blob/9b60ca14d8c45945441a9c95a97ab9bceeebf004/de1plus/plugins/visualizer_upload/plugin.tcl#L182-L183

Admittedly an easy fix, but just annoying everytime I accidentally restore the profile file, I had to remind myself of changing this. Thanks for helping correct this 😊

**Comment by decentjohn** [comment]
fixed.

**Comment by decentjohn** [comment]
Thanks for reporting it so clearly, makes my job easy!
