### ISSUE TITLE
"Factory" setting value changes when making modifications in Settings > Machine > Calibration

### ISSUE THREAD

**Issue by johyphenel** [decentespresso/de1app#260]
In the stable version of the app (v1.39.0.1), changing values in `Settings > Machine > Calibration` causes both the "saved" and "factory" display columns to update, so you lose the ability to know what the setting should be from the factory. 

This seems to also be the case on nightly (v1.40.0.95).

**Comment by decentjohn** [comment]
Yes, I have not yet programmed support for the factory settings feature.  It's on my todo.
