### ISSUE TITLE
JSON overflow

### ISSUE THREAD

**Issue by miharekar** [decentespresso/de1app#267]
Not quite sure what's going on, but JSON that gets sent to Visualizer seem to be corrupted.

<img width="1050" alt="CleanShot 2022-10-07 at 10 48 38" src="https://user-images.githubusercontent.com/986645/194513171-5008778d-6036-4a98-89b8-fb4eebd6b21d.png">

For some reason there's a **key** with profile notes, that has **value** `profile_title`. And when the key (notes) contain new lines, the JSON is invalid. 

Here's an example file:
[2022-10-07T08_31_07Z.json.zip](https://github.com/decentespresso/de1app/files/9732308/2022-10-07T08_31_07Z.json.zip)

**Comment by ebengoechea** [comment]
Does this happen to just some user, or is it general? If just one, my bet is on a corrupted settings.tdb file.

**Comment by miharekar** [comment]
@ebengoechea there's been at least 3 users. I've been trying to get the file, and this is the first one I got. Can follow up, when I have more.

**Comment by ebengoechea** [comment]
I'd say some weird character on the profile notes that is not properly escaped, or corrupted settings. Try to get the settings.tdb file from some user that's experiencing the problem.

**Comment by ebengoechea** [comment]
Confirmed it is corrupted settings. Fixing them manually for the user that has sent me his settings, but as others are experiencing this too, there might be some common cause such as a corrupted profile file or app bug.

**Comment by miharekar** [comment]
Great, thanks @ebengoechea!

**Comment by miharekar** [comment]
The files being uploaded are still faulty, so I don't think it was fixed 😬 Maybe it corrupted itself again?

**Comment by ebengoechea** [comment]
I only fixed the specific `settings.tdb` file for the user that sent it to me (and sent it to him just a couple of hours ago). I'm afraid I can't identify the original source of the problem from that, it can be a faulty profile file or some app bug, so certainly, it may still be happening.

**Comment by Mimoja** [comment]
@ebengoechea can you give me a definition of the faulty characters? Might be a solid idea to fix that on startup and save asap :)

**Comment by ebengoechea** [comment]
Not characters, there were entries in the `settings.tdb` from a profile, that did not make valid Tcl value-pairs but were reversed (`value key` instead of `key value`), like this:
```
0 {}
4 preinfusion_guarantee
4.0 profile_filename
6->4 settings_profile_type
20 pressure_end
 (...)
{Dynamic bloom into pressure extraction. Based on the 'easy blooming' profile structure from Luca and Stephane and modified to primarily target high extraction grinders at high flow rates, typically ending around 3-4.5ml/s. Dial with ratio once grind is giving an ending flowrate in the range. Includes a significant temperature drop that reduces harshness (although the actual temperature drop is much less than programmed). By Joe D. Downloaded from Visualizer

Downloaded from Visualizer} profile_title
```

**Comment by Mimoja** [comment]
ohgod -_-

@johnbuckman Do you see any reason not to purge the settings.tdb at the beginning from all keys not used? Could this break how @Damian-AU does it in DSx? I think metric only uses the system settings and does not introduce its own ones and MC has its own settings file.

**Comment by miharekar** [comment]
@ebengoechea could it be that something goes wrong when downloading the profile from Visualizer via DYE?

**Comment by miharekar** [comment]
It changed on my side that I used to silently swallow these errors, and now I catch them. So it could be, that it was happening before, just not detected 😅
