### ISSUE TITLE
Add settings to profile_vars

### ISSUE THREAD

**Issue by barneyhawes** [decentespresso/de1app#27]
With Metric you can adjust the following settings:

- bean_brand
- bean_type
- grinder_setting
- grinder_dose_weight
- grinder_model*

It would be great to have these added to profile_vars in vars.tcl so that they can be different for each profile.  The alternative would be for me to save them in a separate file, but I would like to avoid that.

\* not yet, but might be implemented in the future!

**Comment by decentjohn** [comment]
Agreed, done.

**Comment by decentjohn** [comment]
https://github.com/decentespresso/de1app/commit/02bdc453d5bec0c3452d08b79c1f0ec953260dc2

**Comment by barneyhawes** [comment]
Great, thanks. Tested and confirmed working as expected.

**Comment by JoanPuig** [comment]
Would it make sense to add basket size and tamping technique as well?

**Comment by decentjohn** [comment]
Basket size makes a lot of sense to me, yeah.

Tamping technique, not really agreeing there.
