### ISSUE TITLE
Where are the automated tests?

### ISSUE THREAD

**Issue by dschinkel** [decentespresso/de1app#275]
As a customer who bought one, how in the world is there no test suite in here?

How are you catching regressions?

How do you know that the code you change still works?  How do you know the behavior is repeatable, reliable, safe?

I'm sorry but as a customer, I expect a more professional codebase to be maintained for a machine sitting in my house with this much behavior dealing with the hardware; hardware that heats up to a very high level; and many levers changing the behavior of that hardware through this software.

**Comment by decentjohn** [comment]
feedback received, but this github is for bugs, so I am closing this.
