### ISSUE TITLE
Syntax highlighting fails in VS Code

### ISSUE THREAD

**Issue by barneyhawes** [decentespresso/de1app#28]
Visual Studio Code gets confused by this line in vars.tcl, which leaves it unable to do syntax highlighting for the rest of the file.

`while {[regsub {^([-+]?\d+)(\d\d\d)} $number "\\1$sep\\2" number]} {}`

I don't have enough familiarity with regex to see if this is a bug or propose a different way to write the function.

![image](https://user-images.githubusercontent.com/853713/100292095-77a75200-2f77-11eb-849a-12ccff1431c5.png)

**Comment by decentjohn** [comment]
I wasn't able to recreate the syntax highlighting problem in Sublime or Komodo.

![Screen Shot 2020-11-26 at 11 39 27 AM](https://user-images.githubusercontent.com/11965250/100305482-2a110080-2fdc-11eb-9708-96ec3f1d17e6.jpg)
![Screen Shot 2020-11-26 at 11 39 21 AM](https://user-images.githubusercontent.com/11965250/100305495-2ed5b480-2fdc-11eb-85e7-df245d43b33e.jpg)

**Comment by decentjohn** [comment]
I'm unsure where VS is having trouble with regexp, which looks correct to me, and tests out correctly.

However, I'm found that sometimes this happens with regexp, and can be solved with a slash \ in the regexp, which doesn't affect its correctness.

ie:
^([-+]?\d+)(\d\d\d)
becomes:
^([\-\+]?\d+)(\d\d\d)

see if that helps VS at all.  If so, test the regexp to make sure it's still working correctly.  As - is a meaningful regexp character, it could be that is the cause of the VS parser trouble.

**Comment by barneyhawes** [comment]
Adding the \ didn't help. I wonder if it is a bug in the VS Code extension for Tcl, which I assume includes specification for syntax highlighting.

**Comment by decentjohn** [comment]
Yes it's definitely a bug, it's just that it's often possible to work around the bug in a way that doesn't break the code.

You can try deleting the regexp part and see if that fixes it. That will tell you if that's where the issue is.

If that's not it, try deleting other parts of the line, until the syntax highlighting starts to work.

**Comment by barneyhawes** [comment]
It's this part: `"\\1$sep\\2"`

Removing the double quotes or replacing them with curly braces solves the syntax highlighting problem but might also break the function.

By the way, I don't know how much this function gets called, but it looks like there would be a small performance increase by moving all the logic into the `if` statement:

![image](https://user-images.githubusercontent.com/853713/100359407-66019100-2fef-11eb-805d-db966c438de2.png)

**Comment by decentjohn** [comment]
This proc is something I found elsewhere, and didn't write.

However, since $sep is hard-defined as , we can simplify the code:

proc commify {number}  {
	while {[regsub {^([-+]?\d+)(\d\d\d)} $number {\1,\2} number]} {}
	if {[ifexists ::settings(enable_commanumbers)] == 1} {
		set number [string map {. , , .} $number]
	}
	return $number
}

can you see if that makes VS happy?  I've changed it to be this way in my code already.

**Comment by decentjohn** [comment]
As to your optimisation, it's not correct.  The enable_commanumbers flag is to swap between . and , as the EU tends to use the opposite number formatting, ie:

1,234.56 (USA)
1.234,56 (France)

**Comment by barneyhawes** [comment]
Yes, that alternative function is parsed OK by the VS syntax highlighting. Thanks!

And yes, my optimisation was wrong!

**Comment by decentjohn** [comment]
That's great.
