### ISSUE TITLE
can't change color of the corners of a dbutton

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#292]
![Screenshot 2024-01-08 at 7 47 01 PM](https://github.com/decentespresso/de1app/assets/11965250/c82d2a48-fdca-454e-867f-9e20221570f5)

When I change a button's outer shape, such as with:
.can itemconfigure profile_4_btn-out -fill "#ff0000"
.can itemconfigure profile_4_btn-btn -fill "#ff0000"

the corner colors are not affected.

**Comment by ebengoechea** [comment]
I'm aware. Problem is that arcs (used for the corners) and lines (used for the borders) have different arguments in Tk canvas commands. You set straight lines color using ``-fill`` but arc lines color using ``-outline``. That's difficult to solve.

In the meantime, use the 4 corners tags to change the color. I will add a common ``-cor`` suffix tag in DUI to change all at the same time:
```
dui item config $page {profile_4_btn-out-nw profile_4_btn-out-ne profile_4_btn-out-se profile_4_btn-out-sw} -outline "#ff0000"
```

**Comment by decentjohn** [comment]
Given your naming convention of tags (ie out-n and out-s) I had assumed you'd do -ne, -nw, etc... but grepping the DUI code, I couldn't find any use of that label.

And when I try it, there is no effect:
`.can itemconfigure profile_4_btn-btn-ne -fill "#ff0000"`

so perhaps the -ne, -nw, etc...  tag naming of corners never happened in code?

**Comment by ebengoechea** [comment]
I'll look into all pending DUI issues when I'm more advanced with my DSx2-DYE integration 

About ``.can itemconfigure``, I thing it expects item IDs and not tag names.

**Comment by decentjohn** [comment]
It takes either:
`[pathName itemconfigure tagOrId ?option? ?value? ?option value ...?]`(https://www.tcl.tk/man/tcl8.0/TkCmd/canvas.htm#M52)

and I use that fact successfully:
`.can itemconfigure profile_1_btn-btn -fill $b1c`

**Comment by ebengoechea** [comment]
Oh, right, too long without programming Tcl. The error was in using ``-fill`` instead of ``-outline``, which is what changes the color of arcs sections, as I commented above.
