### ISSUE TITLE
DUI can't change dbutton symbols correctly

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#304]
If I call
dui item config $::all_pages "profile_back" -symbol "arrow-left"

instead of an arrow, the text "arrow-left" appears.

but when creating the dbutton with the symbol, the correct arrow symbol is used.

@ebengoechea

**Comment by ebengoechea** [comment]
Noted, will check during this weekend.

**Comment by ebengoechea** [comment]
Solved: https://github.com/decentespresso/de1app/commit/c189ee66979f54de4fbf56f1ce11253a9f2fa449
