### ISSUE TITLE
Feature request: double tap

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#306]
would it be possible to add a -doubletap action to controls, like you have done for -longpress ?

Pulak indicates that this would be quite useful for UI design.

Naturally, the first tap would be registered as an action, but the 2nd tap would then cause another action.

It's fairly straightforward for me to program this with DUI currently as one-offs, but I wondered if it wouldn't be better in DUI itself.

**Comment by ebengoechea** [comment]
Yes, should be simple. I've done it manually in DYE some time using bind directly, but can be added as an option.

**Comment by decentjohn** [comment]
Yeah, it was simple to add and I've done so with this proc.  Microsoft uses a 500ms double tap threshold, so that's what I used.  

```
proc is_this_a_double_tap {context} {

	set is_double_tap 0
	if {[info exists ::double_tap_time_track($context)] ==1} {
		set elapsed_since_last_tap [expr {[clock milliseconds] - $::double_tap_time_track($context)}]
		if {$elapsed_since_last_tap < 500} {
			set is_double_tap 1
		}
	}
	set ::double_tap_time_track($context) [clock milliseconds]
	return $is_double_tap
}

```

https://github.com/decentespresso/de1app/assets/11965250/a8cdf4c1-b882-486c-894a-0e62cb5348d7

**Comment by decentjohn** [comment]
now in dui
