### ISSUE TITLE
user profiles do not save and restore hot water temperature; built-in profiles behave differently

### ISSUE THREAD

**Issue by diablodale** [decentespresso/de1app#309]
Hot water temperature values are not saved-within and restored consistently with both built-in and user profiles.
Both built-in and user profiles should have the same behavior.
I prefer they both save-within and both restore.

I did not find a scenario where the hot water weight was changed by a profile. This is inconsistent with hot water temperature being saved and/or restored by some profile types. If hot water temperature is saved within a profile...perhaps the water weight/volume should also be saved. Or....neither...consistently. I can imagine a valid experience being that hot water temperature and weight/volume are not saved or restored with either profile types.

If a user customizes a profile for an Americano, they may want that profile to know the desired hot water temperature and weight/volume. If that is the desired experience, then this issue also exposes the further lack-of-feature 😉 of the missing weight/volume save and restore.

### Setup

* de1pro v1.45
* firmware v1333
* app stable v1.43.12.1
* insight dark skin
* Skale 2 scale associated

### Repro

1. Run app
2. tap settings gear
3. tap presets tab
4. choose Default
5. tap OK
6. tap water tab
7. Verify weight=140g and temp=80c
8. change weight=100g and temp=75c
9. tap settings gear
10. in bottom right new name = "Default 2"
11. tap pig
12. tap OK
13. tap water tab
14. verify weight=100g and temp=75c
15. tap settings gear
16. tap "Default" preset
17. tap OK
18. tap water tab

### Result

The water weight is 100g. It kept the value from step 8 above. Good 🙂
The water temp is 80c. Bad 👎The "Default" profile has overriden the hot water temp with its internal value.
Another profile like "Londonium" can be tapped in step 16. Londonium will overwrite with 70c.

### Repro continued

19. Tap settings gear
20. tap "Default 2" profile
21. tap OK
22. tap water tab

### Result

The water weight is 100g. It kept the value from step 8 above. Good 🙂
The water temp is 80c. Bad 👎 The water temperature from step 8 was not saved into the "Default 2" profile and restored when tapped.

### Expected

Hot water temperature value should behave the same with both built-in and user profiles.

* Both save and restore a hot water temp value -- my preference
* Both do not save and do not restore a hot water temp value

**Comment by decentjohn** [comment]
fixed
https://github.com/decentespresso/de1app/commit/da08df62633cb175efe57b28d7a03f873f315103
