### ISSUE TITLE
Loops in advanced profiles 

### ISSUE THREAD

**Issue by beettlle** [decentespresso/de1app#31]
For both tea and pour over it would be very useful to be able to select a couple of steps and loop over them until one of the Limits (water volume, weight) is hit. For example. I spent a bunch of time extending the Tea profile by adding more “infuse” and “flush” steps over and over so I could make a pot of tea instead of a cup. 

Same with the pour over. I spent more time than I like adding “pulse” and “pause” over and over to make a 2 cup V60, which is really almost double my normal procedure. 

Being able to select “pulse” and “pause” and setting the limit to 1.8x times the original recipe weight would have done the same.

**Comment by decentjohn** [comment]
For loops and fancier conditions, our plan is to soon have a scripting language, that can be sent to the DE1.

As to making longer and fancier advanced shots, I feel your pain, as I have to do a lot of tapping too.  But this is a tablet-based app, and adding more complexity to the app (ie, adding loop support) would just complicate the ui for an unusual case.

Our intention is for all shots fancier than what we have now, the scripting language Should be able to handle them.
