### ISSUE TITLE
how to configure extensions?

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#42]
Maybe if an extension defines a configure proc, you could call it to show controls for it here on this page.

![Screen Shot 2020-12-17 at 11 30 08 AM](https://user-images.githubusercontent.com/11965250/102440607-83100980-405b-11eb-9759-1031976745b2.jpg)

**Comment by Mimoja** [comment]
Yes, i want to do that. The extensions are already exporting their settings in their namespace so that this is explicitly possible.
We also have name / author / description available

**Comment by Mimoja** [comment]
I think this has proven solved :)
