### ISSUE TITLE
Github Actions for PRs

### ISSUE THREAD

**Issue by nicpottier** [decentespresso/de1app#6]
I'll volunteer to put together some github actions to automatically run on commits/PRs/merges.

Some ideas:
 1. I don't know TCL, but it isn't clear there is a failsafe linter in TCL due to it's dynamic nature that won't occasionally have false positives. Looks like maybe running through the interpreter will at least spot super obvious syntax errors, so maybe worth a shot?
 2. Again, haven't explored, but having a super super basic unit test would possibly catch syntax errors since linting is of limited value.
 3. Though I love it and again, not sure on TCL feasibility, but auto-formatting can be a nice thing to have once there are new people committing. Won't bite that off yet though.

Anyways, can look at 1 or 2 if there is interest.

**Comment by Mimoja** [comment]
I think it would be super cool to have at least a minimal amount of liniting. (whitespace etc)
Not sure if building a bigger package is worth it in the relative late stages of this app. It might be a case of diminishing returns.

**Comment by decentjohn** [comment]
Unit testing remains one of the most common uses of Tcl, for example Sqlite https://www.sqlite.org/testing.html

Mostly because Tcl/C bindings are so easy to do.

I agree that it'd be a good idea, especially actually for testing the DE1 firmware correctness.

**Comment by decentjohn** [comment]
For linting, I used to use Komodo from Activestate, which had amazingly good Tcl tools including an excellent lint tool.

They've open sourced it now, and it's available here:
https://sourceforge.net/projects/tclpro/

I've not run it in a decade, though.

**Comment by decentjohn** [comment]
Another amazingly useful aspect of "tclpro" was that it offered a remote debugger.  You could run code on a web server (for instance) on still breakpoint and step through it on your desktop. In theory, this should also work with the de1app and could be useful for debugging issues on the Android tablet.

**Comment by decentjohn** [comment]
There are a few source code formatters out there, which you can find on the tcl wiki, such as
https://wiki.tcl-lang.org/page/frink
https://wiki.tcl-lang.org/page/Reformatting+Tcl+code+indentation

but I'm unsure about this.  

The main "war" with code formatting in C/C++ is brackets, and with Tcl there is a style enforced.

We could require 4-space tab formatting.

Otherwise, though, I think that "easy to read and verify" is the most important thing, and needs a human to assess that.

**Comment by decentjohn** [comment]
For my http://bookmooch.com/ project, which needed to be high performance, I wrote a profiler.  It's fairly easy to include, and could be interesting, especially once we have USB support.  The 10hz BLE rate has limited the need for fast updates of the screen, but USB will change that, and give us faster data in.

[profiler.tcl.zip](https://github.com/decentespresso/de1app/files/5427195/profiler.tcl.zip)
