### ISSUE TITLE
plugins: message_label missing and causes failure; plugin not identified in log messages

### ISSUE THREAD

**Issue by jeffsf** [decentespresso/de1app#71]
On loading of plugins, `message_label` is not available with unclear impact on the plugin-load process.

Further, it is not possible from the logs to determine which plugin is involved.

```
webserver_authentication_key "ChangeMe"
2021-02-23 08:20:27.953 INFO: message_page failed because: 'can't read "::message_label": no such variable'
2021-02-23 08:20:27.953 INFO: setup_images_for_first_page
```

**Comment by Mimoja** [comment]
Should have been addressed with feeeefd82b18c28670bf56fa7983b7cc15b05362, can you confirm you have it in your branch?

**Comment by Mimoja** [comment]
It also has been changed to info page to reduce user annoyance

**Comment by jeffsf** [comment]
Rebasing on v1.34.13 has resolved the issue. Thank you.

Closing
