### ISSUE TITLE
plugins: "Missing" settings.tdb should be ignored

### ISSUE THREAD

**Issue by jeffsf** [decentespresso/de1app#72]
It should not be an error that `settings.tbd` is missing as all plugins do not have settings.

```
error opening binary file: path/to/de1plus/plugins/jmk_hacks/settings.tdb / 'couldn't open "path/to/de1plus/plugins/jmk_hacks/settings.tdb": no such file or directory' / '1' / 
Settings file: 
```

**Comment by ebengoechea** [comment]
@jeffsf I corrected that in my last plugins PR, as DGUI doesn't have settings either, are you testing with the latest beta?

**Comment by jeffsf** [comment]
Commit 0125113 yes?

I'll rebase
