### ISSUE TITLE
plugins: Failures due to: can't read "plugin_name", no such variable

### ISSUE THREAD

**Issue by jeffsf** [decentespresso/de1app#75]
With either a simple or minimal plugin (attached), loading of the plugin fails with 

can't read "plugin_name", no such variable

displayed in a pop-up.

Note that `plugin_name` is set at the top of `plugin.tcl` as it is in the example plugin.

Note also that the substitution into `::plugins::${plugin_name}::description` was performed.

```

# Change package name for you extension / plugin
set plugin_name "jmk_hacks"

# These are chown in the plugin selection page
```
(full code to replicate below)

The logs suggest that `plugin.tcl` was loaded, even if not registered:

```
2021-02-23 11:53:44.764 INFO: Settings file /Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app-devel/de1plus/plugins/DPx_Steam_Stop/settings.tdb not found
2021-02-23 11:53:44.764 INFO: Settings file: amazing_feature 3
list_feature {1, 2, 3}
string_feature {test test}


2021-02-23 11:53:44.765 INFO: Settings file /Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app-devel/de1plus/plugins/jmk_hacks/settings.tdb not found
2021-02-23 11:53:44.765 INFO: ::plugins::jmk_hacks (load) ::plugins::jmk_hacks::description
2021-02-23 11:53:44.765 INFO: ::plugins::jmk_hacks (load complete) ::plugins::jmk_hacks::description
2021-02-23 11:53:44.765 INFO: page_display_change ->infopage
2021-02-23 11:53:44.765 INFO: Loading skin image from disk: /Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app-devel/de1plus/skins/default/1280x800/settings_message.png
2021-02-23 11:53:44.765 INFO: page_display_change image create photo infopage -file /Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app-devel/de1plus/skins/default/1280x800/settings_message.png
returning load_advanced_profile_step
2021-02-23 11:53:44.863 INFO: Switched to page: infopage
2021-02-23 11:53:44.863 INFO: Settings file: auto_upload 1
visualizer_endpoint api/shots/upload
visualizer_password passwd
visualizer_url visualizer.coffee
visualizer_username demo@demo123





```
_There is another pop-up just prior to the following pop-up, but there is no clear evidence of an issue in the logs that I can see._ 

![Screen Shot 2021-02-23 at 11 33 46 AM](https://user-images.githubusercontent.com/1946364/108898947-b081b200-75cc-11eb-9585-30d8267682aa.png)

![Screen Shot 2021-02-23 at 11 45 33 AM](https://user-images.githubusercontent.com/1946364/108898969-b7102980-75cc-11eb-81ed-5fb46eae16d9.png)

```

# Change package name for you extension / plugin
set plugin_name "jmk_hacks"

# These are chown in the plugin selection page

set ::plugins::${plugin_name}::author "Jeff Kletsky"
set ::plugins::${plugin_name}::contact "git-commits@allycomm.com"
set ::plugins::${plugin_name}::version 1.0
set ::plugins::${plugin_name}::description "Current hacks"

msg "::plugins::${plugin_name} (load) ::plugins::${plugin_name}::description"

# preload is called on app start even if the plugin is disabled. Can be used to show
# dynamic informations on the settings overview. Please dont put logic here
# needs to return the page you want to be shown first

proc ::plugins::${plugin_name}::preload {} {
	msg "::plugins::${plugin_name}::preload ::plugins::${plugin_name}::description"
}

# This file will be sourced to display meta-data. Dont put any code into the
# general scope as there are no quarantees about when it will be run.
# For security reasons it is highly unlikely you will find the plugin in the
# official distribution if you are not beeing run from your main
# REQUIRED

proc ::plugins::${plugin_name}::main {} {
	msg "::plugins::${plugin_name}::main ::plugins::${plugin_name}::description"
}

msg "::plugins::${plugin_name} (load complete) ::plugins::${plugin_name}::description"
```

**Comment by ebengoechea** [comment]
@jeffsf Sure. You cannot use $plugin_name **inside** your namespace procs, only on the global context, so in procs names.

**Comment by Mimoja** [comment]
I have finally given up trying to make namespaces look like they are anything else.
https://github.com/Mimoja/de1app/blob/staging/de1plus/plugins/example/plugin.tcl
Then you can you use local variables. Need to find a nice way to do that with array tho :/

**Comment by jeffsf** [comment]
Thanks @Mimoja that looks like a robust approach.

I assumed that declaring the plugin name would have created a namespace variable, so that it wouldn't have to be redeclared and set in the namespace by the author.

We're all stuck with the Tcl "anti-feature" of looking up unqualified names in the global namespace if they haven't been explicitly declared with `variable` or a fully qualified name, complicated by not having a `local` built-in, but at least that's not hidden, if not well known. I continue to have a concern that even implicit, local variables, such as `f` in `foreach f in $files` may unexpectedly trash globals.

Ref: https://www.tcl.tk/man/tcl8.6/TclCmd/namespace.htm#M26

> Variable names are always resolved by looking first in the current namespace, and then in the global namespace.

Ref: Nadkarani, Ashok P., _The Tcl Programming Language: A Comprehensive Guide,_ 2017, pg. 325

> This is an acknowledged misfeature which is currently preserved for backward compatibility and will probably be fixed in the next manor Tcl release.
