### ISSUE TITLE
fast_write_open is duplicated

### ISSUE THREAD

**Issue by ebengoechea** [decentespresso/de1app#76]
Proc 'fast_write_open' is defined twice, once in updater.tcl, and again in bluetooth.tcl. Which one is called and why? Because 'bluetooth.tcl' is sourced in setup_environment, in my tests I've found that it is normally the version in bluetooth.tcl that is being called in the code, for example when saving the settings files. 

But, know what? They are quite different. For example, I spotted a bug with the settings on PC some time ago (doesn't happen on other platforms), that new lines could get duplicated. @decentjohn solved it on the 'fast_write_open' in updater.tcl by changing argument -translation of the fconfigure command to {lf lf}. But I am experiencing the same bug again now, and have found that it is because 'fast_write_open' in updater.tcl is NOT being called, it is the one in bluetooth.tcl that is being called, and that version was never updated.

Why this command is duplicated and why such a commonly invoked proc (whenever saving settings) is defined in files "updater" and "bluetooth" is beyond me. Don't know at this point what the adequate correction should be.

**Comment by decentjohn** [comment]
Likely duplicated by accident because I wanted the cloud updater to have an absolute minimum set of .tcl dependencies, but this call was needed for the cloud updater app.

Can I ask you to remove the one in bluetooth.tcl and confirm the app works fine?  If so, then submit that removal as a PR?

**Comment by ebengoechea** [comment]
@decentjohn I've had the version on bluetooth.tcl commented on my tablet & PC for the last couple of days without apparent side effects. I'll test a bit more and do a PR.

**Comment by ebengoechea** [comment]
Was solved by #81
