### ISSUE TITLE
skins: Profile pick list improperly handles `category/something/profile string`

### ISSUE THREAD

**Issue by jeffsf** [decentespresso/de1app#80]
When profile_title contains a slash, the first word is understood to be a "category" for rendering in the GUI in an indented form under the category, with the remainder of the title visible.

However, if multiple slashes are present, such as in `profile_title {jmk/Adaptive/Rao Allongé}`, the remainder is not rendered.

To replicate:
* Select `adaptive_blooming.tcl`
* Edit the profile title in an external editor and change the line to `profile_title {jmk/Adaptive/Rao Allongé}`
* Upload to the DE1 `profiles/` directory
* Restart the app
* Navigate to the profile selector screen
* Note that only "- Adaptive" appears in the picker for the list of profiles for the edited profile

Expected:
* "-Adaptive/Rao Allongé" would appear

Suggested resolutions:
* Minimal; include the remainder of the title, as shown above
* Ideal; multiple levels of indentation

**Comment by jeffsf** [comment]
![Screenshot_20210301-120328](https://user-images.githubusercontent.com/1946364/109553062-65ade180-7a87-11eb-8c5b-eaa435091321.png)

**Comment by decentjohn** [comment]
This was by design for the tab title, as there isn't enough space for 3 lines of text.

However, this is a bug for the listbox, and multiple levels of indentation would be ideal.  I don't think it'd be difficult to adapt the code to do this.

I don't think you need to use an external app to cause this bug, you can likely cause it by having a two//slash title in the UI itself.

**Comment by jeffsf** [comment]
I don't mind having the slash in the listbox or tab title.

Even being able to group "my" working copies from the originals is a significant improvement in usability.

True, you can probably do the same in the edit box.

**Comment by decentjohn** [comment]
@jeffsf do you think you're up to the task of modifying the listbox "slash/category" handler to correctly handle another sublevel?

If not, no problem, I can put it on my todo.

![Screen Shot 2021-03-05 at 2 31 23 PM](https://user-images.githubusercontent.com/11965250/110076520-93649480-7dbf-11eb-8f11-eec0c65ad6c9.jpg)
