### ISSUE TITLE
1.34.16: scroll bar for preset selection is missing

### ISSUE THREAD

**Issue by physhster** [decentespresso/de1app#82]
I believe this is a new defect, the scroll bar in the preset selection screen has disappeared in 1.34.16. Restarting the app doesn't bring it back.

<img width="573" alt="Screen Shot 2021-03-03 at 17 24 56" src="https://user-images.githubusercontent.com/10538336/109896253-76a45180-7c45-11eb-8891-daf0f0aa5d2c.png">

**Comment by physhster** [comment]
Issue still exists in 1.34.27, @decentjohn

**Comment by Mimoja** [comment]
Was fixed a while back, MimojaCafe was not calling the scrollbar function properly
