### ISSUE TITLE
Unreachable code in load_settings_vars

### ISSUE THREAD

**Issue by ebengoechea** [decentespresso/de1app#84]
While making the PR #83, I've found this code in vars.tcl, ``proc load_settings_vars``. Because ``temp_settings`` is a **local** variable, not a global one, I think the code in the inner block is never reached, which doesn't seem intended.

I'm not doing a PR because I'm not sure whether the intention is to have ``[ifexists ::settings(black_screen_saver)]`` or ``[ifexists temp_settings(black_screen_saver)]``.

```tcl
	if {[ifexists ::temp_settings(black_screen_saver)] == 1} {
		# we've moved the "black screen saver" feature from its own dedicated variable to now be a setting of "0 minutes" on the screen saver change timer
		# this line is simply for backward compatiblity, moving the old setting to a new one
		set temp_settings(final_desired_shot_volume) 0
		set temp_settings(saver_brightness) 0		
	}
```

**Comment by jeffsf** [comment]
@decentjohn ?

**Comment by decentjohn** [comment]
I'm not seeing an obvious bug.  

temp_settings is filled earlier with this:

```
	catch {
		foreach {k v} [encoding convertfrom utf-8 [read_binary_file $fn]] {
			#puts "$k $v"
			#set ::settings($k) $v
			set temp_settings($k) $v
		}
	}
```

and then later set globally with this:

```
	catch {
		array set ::settings [array get temp_settings]
	}

```
fyi in 
`proc load_settings_vars {fn} {`

If I'm misunderstanding, please do correct me.

**Comment by ebengoechea** [comment]
@decentjohn I understand that if temp_settings is a **local** variable, using **::**temp_settings (with the double colon at the beginning) in the `if` condition only searches it in the global context, and not in the local proc context, isn't that the case?

`if {[ifexists ::temp_settings(black_screen_saver)] == 1}`

**Comment by decentjohn** [comment]
gotcha, thanks for persisting. yes, and fixing.
